from enum import StrEnum


class ErrorCode(StrEnum):
    # Generic
    BAD_REQUEST = "BAD_REQUEST"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"

    # Auth
    UNAUTHORIZED = "UNAUTHORIZED"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"  # nosec B105
    FORBIDDEN = "FORBIDDEN"
    INACTIVE_USER = "INACTIVE_USER"

    # Resources
    NOT_FOUND = "NOT_FOUND"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    ORDER_NOT_FOUND = "ORDER_NOT_FOUND"

    # Conflicts
    CONFLICT = "CONFLICT"
    USER_EXISTS = "USER_EXISTS"
    EMAIL_ALREADY_VERIFIED = "EMAIL_ALREADY_VERIFIED"

    # Rate limiting
    RATE_LIMITED = "RATE_LIMITED"
